// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type BorderCode struct {
	Code       string
	Descr      string
	WxxFeature string
}

type Clan struct {
	ID   int64
	Name string
}

type ItemCode struct {
	Code  string
	Descr string
}

type Move struct {
	ID            int64
	ClanNo        int64
	TurnNo        int64
	UnitID        string
	StepNo        int64
	StartingTile  int64
	Action        string
	EndingTile    int64
	TerrainCd     string
	FailureReason sql.NullString
	ParseError    sql.NullString
}

type MoveBorderDetail struct {
	MoveID   int64
	BorderCd string
	Edge     string
}

type MovePassageDetail struct {
	MoveID    int64
	PassageCd string
	Edge      string
}

type MoveResourceDetail struct {
	MoveID     int64
	ResourceCd string
}

type MoveSettlementDetail struct {
	MoveID int64
	Name   string
}

type MoveTransientDetail struct {
	MoveID int64
	UnitID string
}

type PassageCode struct {
	Code       string
	Descr      string
	WxxFeature string
}

type ReportFile struct {
	ID        int64
	Hash      string
	Name      string
	CreatedAt int64
}

type ResourceCode struct {
	Code       string
	Descr      string
	WxxFeature string
}

type TerrainCode struct {
	Code       string
	IsHills    int64
	IsJungle   int64
	IsMountain int64
	IsSwamp    int64
	IsWater    int64
	LongCode   string
	Descr      string
	WxxTerrain string
}

type Tile struct {
	ID            int64
	Grid          string
	Row           int64
	Col           int64
	North         sql.NullInt64
	NorthEast     sql.NullInt64
	NorthWest     sql.NullInt64
	South         sql.NullInt64
	SouthEast     sql.NullInt64
	SouthWest     sql.NullInt64
	LastVisitedOn sql.NullInt64
	LastScoutedOn sql.NullInt64
}

type TileBorderDetail struct {
	TileID    int64
	Effdt     int64
	Enddt     int64
	BorderCd  string
	Direction string
}

type TilePassageDetail struct {
	TileID    int64
	Effdt     int64
	Enddt     int64
	PassageCd string
	Direction string
}

type TileResourceDetail struct {
	TileID     int64
	Effdt      int64
	Enddt      int64
	ResourceCd string
}

type TileSettlementDetail struct {
	TileID int64
	Effdt  int64
	Enddt  int64
	Name   string
}

type TileTerrainDetail struct {
	TileID    int64
	Effdt     int64
	Enddt     int64
	TerrainCd string
}

type TileTransientDetail struct {
	TileID int64
	Effdt  int64
	Enddt  int64
	UnitID string
}

type Turn struct {
	ID    int64
	Year  int64
	Month int64
}

type Unit struct {
	ID      string
	ClanNo  int64
	IsScout int64
}
