= TribeNet Turn Report

This is not official TribeNet documentation.
It is my understanding of a report layout.

I'm only documenting the bits that are used by OttoMap to generate the map.

== Common Terms

I assume that you're familiar with TribeNet, so these definitions are very informal.

. Coordinates - measure rows and columns from the upper-left corner of the grid or map
.. Rows start at 1 increase top to bottom.
.. Columns start at 1 increase left to right.
. Grids - identified by two letters encoding the Row and Column.
 The upper-left grid is AA and the bottom-right is ZZ.
 The grid in row 2, column 3 is BC.
. Maps - each grid contains a map that is 30 hexes wide by 21 hexes tall.
. Directions - North is at the top of the map.
 The codes are N, NE, SE, SW, and S.
. Hex - each hex on a map is identified by Column then Row (this is the opposite of Grids!).
 Both are always two-digit numbers (e.g., 01, not 1).
 The upper-left hex is 0101 and the bottom-right is 3021.
 Hexes have details like terrain, edges, and settlements.
. Terrain - every hex has a terrain code.
 The report uses both names (Swamp and Ocean) and short codes (SW and O).
. Edge - every hex has six edges, each identified by the direction from the center of the hex.
 Edges are called out in a report only when they're significant.
. Border - an edge can have a feature like a river or canal that separates two hexes.
 Usually a border will prevent units from moving between the hexes; sometimes not.
. Passage - an edge can be crossed by something like a ford or mountain pass.
 These are called passages because they sometimes allows a unit to cross a border that it normally couldn't.
. Resources - things like ore deposits
. Settlements - named villages
. Location - all hexes have a location that tells us which grid they're on and their column and row on that grid.
The location looks like "AA 0101."
. Unit - each player controls units and every unit has a unique identifier.
.. Tribe - tribe units are identified by a four-digit number
.. Courier - courier units are identified by a four-digit number followed by the letter "c" and a single digit sequence number.
.. Element - element units are identified by a four-digit number followed by the letter "e" and a single digit sequence number.
.. Fleet - fleet units are identified by a four-digit number followed by the letter "f" and a single digit sequence number.
.. Garrison - garrison units are identified by a four-digit number followed by the letter "g" and a single digit sequence number.
. Clan - the tribe that starts with "0."

See https://tribenet.wiki/mapping/grid for details on the grids and maps.

== Layout

All turn reports contain a section for each unit that they are reporting.
The sections have a header for the unit, information on the turn, movement and scouting results, and a status line for the unit.

=== Unit Header

The unit header contains four fields that are separated by commas:

1. Unit type
2. Unit name
3. Current Hex
4. Previous Hex

----
Tribe 0987, , Current Hex = KP 0608, (Previous Hex = ## 0608)
Courier 0987c1, , Current Hex = KP 0810, (Previous Hex = ## 0608)
Element 0987e1, , Current Hex = LP 2001, (Previous Hex = ## 2021)
Fleet 0987f1, , Current Hex = KR 0708, (Previous Hex = N/A)
----

The Previous Hex value is where the unit started the turn.
This can sometimes be "N/A," which means the unit was created before this turn started.
Usually, though, it is the grid and map location, with the grid being obscured (the grid is replaced with "##).

The Current Hex is where the unit ended the turn.
In early turn reports, the grid is obscured.
Starting around turn FIXME, the grid is provided.

The first unit in your report should be your clan.

=== Turn

Each section contains a line with the turn number for the report.

The format is a little bit weird since it has an optional part.

The first part consists of three comma separated fields:

1. Current Turn
2. Season
3. Weather

----
Current Turn 900-05 (#5), Summer, FINE
----

All of your units get the first part.

The second part is optional and is provided only for your clan.
It contains two comma separated fields:

1. Next Turn
2. Report Date

----
Next Turn 900-06 (#6), 14/01/2024
----

If the second part is present, it is separated from the first by a tab.
(That's the weird bit, since fields in the header are usually separated by commas.)

----
Current Turn 900-05 (#5), Summer, FINE Next Turn 900-06 (#6), 14/01/2024
----

==== Current Turn Format
The Current Turn section contains the year, month, and turn number.

=== Tribe Movement

----
Tribe Movement: Move NE-PR\SE-PR\SE-GH\SE-PR, O S W, Ford SE\SE-GH,O SW SE, River N, Ford NW,Los Angeles
Tribe Movement: Move NW-PR\SW-PR,O NW, River S, Ford SW\SW-PR, O N, Ford NE\SW-PR\Not enough M.P's to move to SW into GRASSY HILLS
----

The movement line consists of the "Tribe movement: move" prefix followed by any number of individual steps.
The steps are separated by backslashes.

Each step usually contains a direction-terrain code followed by a comma separated list of results (or observations).

The results for a step list border features (oceans, lakes, rivers, canals), passages (fords, passes), then settlements.

A hex can have borders and passages on any edge, so the result lists the feature and the edge it is on.
For example, "river n" means there is a river on the northern edge of the hex.
The feature can be on multiple edges.
When that happens, the directions are listed and separated by spaces.
A result of "river n ne se" means that the river is on the northern, north-eastern, and south-eastern edges of the hex.

A hex can also have neighbors like oceans, lakes, and mountains that are visible from it.
The step for those will look like:

----
O NW NE
----
or
----
L S SE
----
or
----
LJM N
----

The step will start with "not enough m.p's" only if the unit attempted to move and the destination hex's terrain required more movement points than were remaining for the unit.

If the tribe doesn't move during the turn, they will still get a movement line, but it will be empty:

----
Tribe Movement: Move
----

=== Tribe Follows

=== Tribe Goes To

=== Fleet Movement

=== Scout

Each section may contain up to eight scout lines.

The results of patrols look like:

----
Scout 1: Scout N-GH\N-SW\Not enough M.P's to move to N into PRAIRIE,Nothing of interest found
Scout 2: Scout N-PR\N-GH\N-RH,O NW N,Find IRON ORE,0987 0987c2 0987c3\Can't move on Ocean to N of HEX,Patrolled and found 0987 0987c2 0987c3
Scout 3: Scout SE-PR\SE-PR\SE-PR\SE-PR,L S\SE-PR,L SW,River SE S SW\No Ford on River to SE of HEX,Nothing of interest found
Scout 7: Scout NW-RH\N-GH\N-PR,O NW N,3987,Can't move on Ocean to N of HEX,Patrolled and found 3987
Scout 8: Scout SE-PR\SE-PR\S-PR\S-GH,River S\No Ford on River to S of HEX,Nothing of interest found
----

The format is similar to the Tribe Movement line but includes more information.
Scouts on patrol will find resources and other units as they move.

If the result includes multiple resources, they will be space separated.

If the result includes multiple units, they will be space separated.

The last step will include a result starting with "nothing of interest found" if the scout found no resources or other units during any of their steps.
Otherwise, it will include a result starting with "patrolled and found."

=== Status

----
0987 Status: PRAIRIE,0987
0987c1 Status: GRASSY HILLS,Los angeles,O SW,River N,Ford NW,0987c1 0987e1 0987e1 1987g1 2987c1
0987c2 Status: ROCKY HILLS,Iron Ore,O NW N,0987c2 0987c3 1987
3987g1 Status: CONIFER HILLS,Coal,O SW,2987e1 3987g1
----

*Note*: I think that the order of the results is slightly different from moves and scouts.
Not sure if settlements are before or after resources.